version: "3.7"
services:
  client:
    container_name: yolomy_client
    restart: unless-stopped
    build: client/
    ports:
      - 3000:3000
    networks:
      - yolomy

  backend:
    container_name: yolomy_backend
    restart: unless-stopped
    build: backend/
    ports:
      - 5000:5000
    depends_on:
      - mongo
    networks:
      - yolomy

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
    networks:
      - yolomy

networks:
  yolomy:
    driver: bridge

volumes:
  dbdata: